import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SkillSync",
  keywords: ["Next.js", "React", "SkillSync", "Web Development"],
  authors: [
    {
      name: "SkillSync Team",
      url: "https://skillsync.com",
    },
  ],
  creator: "SkillSync Team",
  openGraph: {
    title: "SkillSync",
    description: "A platform to sync and enhance your skills",
    url: "https://skillsync.com",
    siteName: "SkillSync",
    images: [
      {
        url: "https://skillsync.com/og-image.png",
        width: 1200,
        height: 630,
        alt: "SkillSync Open Graph Image",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
